M48
; DRILL file {KiCad 7.0.8} date 2025 May 01, Thursday 09:06:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-01T09:06:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0492
%
G90
G05
T1
X2.18Y-1.282
X2.28Y-1.288
T2
X1.626Y-0.6732
X1.814Y-1.516
T0
M30
